# First draft as a good start. Let's do it in a decent way.

import os, sys
Import('prog_name')

if sys.platform.startswith('win32'):
    compiler_tool_chain = 'mingw'
else:
    compiler_tool_chain = 'default'
env = Environment(tools=[compiler_tool_chain, 'textfile'], ENV=os.environ)

c_srcs = Glob('src/*.c')

env.MergeFlags('-pthread -lpthread')

libs=['radar_sdk']
if not sys.platform.startswith('linux'):
    env.Append(LINKFLAGS='-static')
    libs.append('winmm')
else:
    libs.append('wiringPi')

env.Program(os.path.join('build', prog_name),
             c_srcs,  
             CPPPATH=['../../inc/radar_sdk', 'inc'], 
             LIBPATH=['../../libs'], 
             LIBS=libs)
